import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ActiveLink } from '@/ui/atoms/ActiveLink';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
    <body className={inter.className}>

    <nav>
      <ul className={'flex justify-center space-x-4 mt-2'}>
        <li><ActiveLink href="/">Home</ActiveLink></li>
        <li><ActiveLink href="/products">Products</ActiveLink></li>
      </ul>
    </nav>

    <section className={'mx-auto h-full max-w-md p-12 sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl'}>
      {children}
    </section>

    <footer className={'text-center h-12 bg-red-500'}>
      2024
    </footer>
    </body>
    </html>
  );
}
